In [1]:
! pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

In [4]:
list=[1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]


In [5]:
array=([1,2,3,4,5])
print(array)

[1, 2, 3, 4, 5]


In [6]:
print(type(array))

<class 'list'>


In [8]:
array= np.array([1,2,3,4,5])
print(array.ndim)

1


In [9]:
array= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array.ndim)

2


In [11]:
array= np.array([[1,2,3,4,5],[6,7,8,9,10]])
t=array.T
print(t)


[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [12]:
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1_2 = np.array([list1, list2])
print(arr_list1_2)

[[1 2 3]
 [4 5 6]]


In [13]:

arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1)


[[1 2 3]
 [4 5 6]]


In [14]:
print("Shape", arr1.shape)  
print("Size", arr1.size)    
print("dType", arr1.dtype)  
print("n_dim", arr1.ndim)   

Shape (2, 3)
Size 6
dType int64
n_dim 2


In [19]:
print(array[:0])

[]


In [20]:
array= np.zeros(2)
print(array)

[0. 0.]
